#these can come from fmriprep:
in_preproc_T1w: '/project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz'
in_brainmask_T1w: '/project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/brainmask_fs.nii.gz'

#this can come from raw bids:
#in_raw_T2w: '/project/6050199/akhanf/ext-bids/cam-can/bids/combined/sub-{subject}/anat/sub-{subject}_T2w.nii.gz'



#for template building - mix of fmriprep and internally processed-data
in_images:
  T1w: '/project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz'
  T2w: '/project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T2w_acpc_dc_restore_brain.nii.gz'
  GM:  'results/preproc/sub-{subject}/sub-{subject}_space-T1w_label-GM_probseg.nii.gz'
  WM:  'results/preproc/sub-{subject}/sub-{subject}_space-T1w_label-WM_probseg.nii.gz'


#for naming the final files in templateflow output
bids_suffix:
  T1w: 'desc-brain_T1w'
  T2w: 'desc-brain_T2w'
  GM: 'label-GM_probseg'
  WM: 'label-WM_probseg'



cohorts:
  - UR100
#  - 7Tsubj

participants_tsv:
  UR100: 'config/participants_HCP_UR100.tsv'

extra_participants_tsv: /scratch/akhanf/3_processing/diffparc-smk/config/hcp7Tparticipants.tsv



#for templateflow-style output
template_name: 'HCP1200'  #tpl-{template_name} 


resolution_index: 1 # res-{resolution_index}
#shape, zooms, origin will be obtained from the nifti itself


#for creating the template_description.json file
template_description_extras:
  Name: 'Brief template description goes here'
  Authors:
    - 'Your Name Here'
  Acknowledgements: 'Created by ants_build_template_smk Snakemake workflow'
  BIDSVersion:
    - '1.1.0' 
  License: 'See LICENSE file'
  TemplateFlowVersion: '1.0.0'


#assumes that templateflow templates are linked in resources folder
init_template:
  T1w: 'resources/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-04_desc-brain_T1w.nii.gz'
  T2w: 'resources/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-04_desc-brain_T2w.nii.gz'
  GM: 'resources/templateflow/tpl-MNI152NLin6Asym/FSL_FAST/tpl-MNI152NLin6Asym_res-04_desc-brain_T1w_prob_1.nii.gz'
  WM: 'resources/templateflow/tpl-MNI152NLin6Asym/FSL_FAST/tpl-MNI152NLin6Asym_res-04_desc-brain_T1w_prob_2.nii.gz'

#will register cohort templates to the std template after they are generated
std_template_name: 'MNI152NLin2009bAsym'

#keep this empty, is set by command-line ( --config run_iter=1 or --config run_cohort=young)
run_cohort: 
run_iter: 
run_composite: True

#this is the iter which is exported into templateflow format
max_iters: 8


resample_init_template: True #set this True to resample init template to below dims 
# WARNING - changing this can significantly alter memory usage and run-time -- 
resample_vox_dims: 
 - 1
 - 1
 - 1



#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
singularity:
  prepdwi: '/project/6050199/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif'  
  ants:  '/project/6050199/akhanf/singularity/kaczmarj_ants_2.3.4.sif'
  itksnap:  '/project/6050199/akhanf/singularity/pyushkevich_itksnap_latest.sif'

ants:
  dim: 3
  shape_update:
      gradient_step: 0.25



